sudo: required
language: node_js
node_js:
- node
cache: npm
jobs:
  includes:
  - stage: build and deploy
  before_script:
  - npm install
  script: echo "npm test temporarily disabled"
deploy:
  provide: heroku
  api_key:
    secure: tPHSVPoVt72wcMhy+6/EAIWu7Ch2Vnart/VgbwM5rwSgfiF7DUJ6weO1AxuT2zAv70ORgEkpqePD2EuCTwShux0PWVBUjrO5Tww6nfoJcpodtABRj62r2RlyOkON2PZWARvnDyNprHz/zlE6p7m7ptNA03vsEKa2DxQMe7D/aOhMhM0hcrsV+qMaiPGFCxj/lciUzxf9dccrf0PwJ11LMRNc/kBPTgK0qXtsK/dLVs7NJf3sETpQ/coBXZAqoK0Vf484KVoCcNF26TEwyDpocIrE7WXN/wheNU9LmHyFQMLF7WCeRso60HXIfKPkkQrL+vKuRjSean4R3DkRJQnYgLCojQhr4lb1ieBZg7rSdVYr2S/iPoZv2zSFjw7p2XmVrcNZq0+9j2uq8H9MHB76Gsru3JxKQQZaOXb5K/dvQSXc5OCdnaS4YrRe1vsQyX4JFJwif+ArFBLzqJKv4rwKma2o8Zj7fSl+BR2HKiCUBbiZ+tEJyrd5jyBJAut827WzHb2USgBKKQx3+u9vqiTDglmbL/Y84lgudkca0hNRIyHNvWmq7/5fLyYHNzVy8VPiq902kzyGIv04GRTgHlJvHfN1gDIIa6TZgrWboifNnswLpNSWw/wlE/QLtCaf2mL5lD6k6JH6ELI+CbCnAVaICyPoh5KH1mE7M64OqDkyIzA=
  app: game-200mph
