sudo: required
services:
- docker
before_install:
  - wget -q0- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" password-stdin registry.heroku.com
  script:
    - docker build -t mfjv88/200mph .
    - docker tag mfjv88/200mph registry.heroku.com/$HEROKU_APP_NAME/web

  deploy:
    provider: script
    script:
      docker push mfjv88/200mph;
      docker push registry.heroku.com/$HEROKU_APP_NAME/web;
      heroku container:release web --app $HEROKU_APP_NAME
    on:
      branch: master
