sudo: required
language: node_js
node_js:
- node
cache: npm
jobs:
  includes:
  - stage: build and deploy
  before_script:
  - npm install
  script: echo "npm test temporarily disabled"
deploy:
  provide: heroku
  api_key:
    secure: gh9nIo+ZTnVteURo6FNzgIPk3DlFZDWpZy8V2a5ufZ92pCRiDprJrwhQUKqMP2KLwdD2bwO7adUDqI+McQFvfr4vHWIZyx1RsUFPsWqMRbP2MAcfjfqXRZQKPkySyWaJj0JOWKiPOHZYUCbP6ufXu7JOBuaJz7eg+gFHV5cwVoxQnsQW2rchXrE4XOWyAVS/mK+rl5sr61PLf2X7wFbqHA+WCONCp7uD0OwRi/e24JA0WlUJ8tD+G9o9aOKhZSHTPVZRur7LBOaC42eRFNEwrbtQGxo2yIuSNom5PXQCdGc/INfvEygN8pGYb9iXCbiLF1VWPRRiAFJXC3flp70ZpUuyh9TnZ4M3znJWuYQGMmGlEmBOF1oOakurb1TrndOOmJGBjQheDmIe37AtG0OKBT/okGmqDTWCyScLBlcNm3HY7Y1WIZHBROPQYBZFBQj0WDKGJhzx8fx4oZUNEQm8Gd4lsKffhGqumF8qrqagDt3xWT+iWPKCVDKUC8nBL6LtDnCFC4aiJboSvR/EZ60jOq2PqvWojGSbBslUBUoxYVL2KtxwNpl0HhD4PqLdrcSO+u/CLdSIuW0wGCzDSOBNinodT2fv32OJNB8DeHTDHKGeGiAqV+taYrbMbfeL01okDdX4Fw6MeT1wZjnSlpFSuCH4tF0Kz/UXxAsqPaOpqo4=
  app: game-200mph
